export const STORAGE_KEYS = {
  LIBRARY: "wa_library_v1",
  SETTINGS: "wa_settings_v1",
  SENTENCE_REMOVAL: "wa_sentence_removal_v1",
  REGEX_CLEANUP_RULES: "wa_regex_cleanup_rules_v1",
  TTS_SETTINGS: "wa_tts_settings_v1",
  TTS_SESSION: "wa_tts_session_v1",
  CHAPTER_FILTER_SETTINGS: "wa_chapter_filter_settings_v1",
  TABS: "wa_tabs_v1",
  FOLD_LAYOUT_MODE: "wa_fold_layout_mode_v1",
  SOURCE_DOWNLOAD_SETTINGS: "wa_source_download_settings_v1",
  THEME_DARK_VARIANT: "wa_theme_dark_variant_v1",
  THEME_LIGHT_VARIANT: "wa_theme_light_variant_v1",
  THEME_FOLLOW_SYSTEM: "wa_theme_follow_system_v1",
  THEME_MODE: "wa_theme_mode_v2",
  THEME_ACTIVE: "wa_theme_active_v1",
} as const;
